services:
  tictactoe:
    image: tictactoe
    build:
      context: .
      dockerfile: TicTacToe.API/Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - BoardSize=${BoardSize}
      - WinCondition=${WinCondition}
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  pgdata:
        
    

