services:
#  tictactoe:
#    image: tictactoe
#    build:
#      context: .
#      dockerfile: TicTacToe/Dockerfile
      
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  pgdata:
        
    

